---
# tasks file for roles/app

- name: Launch backend container
  docker_container:
    name: backend
    image: lam45/project-docker-backend:latest
    state: started
    restart_policy: always
    networks:
      - name: project_network
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/db
    published_ports:
      - "8082:8080"
  tags: ["app"]  
