name: CI devops 2025

on:
  push:
    branches:
      - main
      - develop

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn clean verify --file ./backend/pom.xml

      - name: Analyse avec SonarCloud
        working-directory: ./backend
        run: |
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=lamT45_Project-Docker \
            -Dsonar.organization=lamt45 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
