name: CI devops 2025

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      # 1. Checkout le code GitHub
      - uses: actions/checkout@v4

      # 2. Installer Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Build et test Maven
      - name: Build and test with Maven
        run: mvn clean verify --file ./backend/pom.xml

