name: CI devops 2025
on:
  # Déclenche le workflow sur push vers main et develop
  push:
    branches: 
      - main
      - develop
  pull_request:

jobs:
  # Job 1: Tester l'application backend
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
      # Étape 1: Récupérer le code depuis GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2: Installer JDK 21 (nécessaire pour compiler le projet Java)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Étape 3: Compiler et tester avec Maven
      # Commande: mvn clean verify
      # - clean: nettoie les anciens builds
      # - verify: compile, teste (unit tests + integration tests avec testcontainers)
      - name: Build and test with Maven
        run: mvn clean verify --file ./backend/pom.xml